export default {
    ADMINISTRATOR: "Administrador",
    VIEW_AUDIT_LOG: "Ver o registro de Auditoria",
    MANAGE_GUILD: "Gerenciar Servidor",
    MANAGE_ROLES: "Gerenciar Cargos",
    MANAGE_CHANNELS: "Gerenciar Canais",
    KICK_MEMBERS: "Expulsar Membros",
    BAN_MEMBERS: "Banir Membros",
    CREATE_INSTANT_INVITE: "Criar Convites",
    CHANGE_NICKNAME: "Mudar Apelido",
    MANAGE_NICKNAMES: "Gerenciar Apelidos",
    MANAGE_EMOJIS: "Gerenciar Emojis",
    MANAGE_WEBHOOKS: "Gerenciar Webhooks",
    VIEW_CHANNEL: "Ler Canais de Texto e Ver Canais de Voz",
    SEND_MESSAGES: "Enviar Mensagens",
    SEND_TTS_MESSAGES: "Enviar Mensagens em TTS",
    MANAGE_MESSAGES: "Gerenciar Mensagens",
    EMBED_LINKS: "Incorporar Links",
    ATTACH_FILES: "Anexar Arquivos",
    READ_MESSAGE_HISTORY: "Ver Histórico de Mensagens",
    MENTION_EVERYONE: "Mencionar @everyone, @here e Todos os Cargos",
    USE_EXTERNAL_EMOJIS: "Usar Emojis Externos",
    ADD_REACTIONS: "Adicionar Reações",
    CONNECT: "Conectar em um Canal de Voz",
    SPEAK: "Falar em um Canal de Voz",
    STREAM: "Transmitir Vídeos em um Canal de Voz",
    MUTE_MEMBERS: "Silenciar Membros",
    DEAFEN_MEMBERS: "Ensurdecer Membros",
    MOVE_MEMBERS: "Mover Membros para outros Canais de Voz",
    USE_VAD: "Usar Detecção de Voz",
    PRIORITY_SPEAKER: "Voz Prioritária"
};